version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  labels:
    - "Dependencies"
  versioning-strategy: auto
  
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: 'daily'
  labels:
    - "Dependencies"
